# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-12 08:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='yx_api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('crttime', models.DateTimeField(auto_now=True, verbose_name='CreateTime')),
                ('data', models.CharField(blank=True, max_length=255, verbose_name='Data')),
            ],
        ),
        migrations.CreateModel(
            name='yx_sp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, verbose_name='URL')),
                ('crttime', models.DateTimeField(auto_now=True, verbose_name='CreateTime')),
                ('data', models.CharField(blank=True, max_length=255, verbose_name='Data')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='yx_sp',
            unique_together=set([('url',)]),
        ),
        migrations.AlterUniqueTogether(
            name='yx_api',
            unique_together=set([('url',)]),
        ),
    ]
